/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealPlannerIndexRouteImport } from './routes/meal-planner/index'
import { Route as MealPlannerLandingRouteImport } from './routes/meal-planner/landing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlannerIndexRoute = MealPlannerIndexRouteImport.update({
  id: '/meal-planner/',
  path: '/meal-planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlannerLandingRoute = MealPlannerLandingRouteImport.update({
  id: '/meal-planner/landing',
  path: '/meal-planner/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meal-planner/landing': typeof MealPlannerLandingRoute
  '/meal-planner/': typeof MealPlannerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meal-planner/landing': typeof MealPlannerLandingRoute
  '/meal-planner': typeof MealPlannerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meal-planner/landing': typeof MealPlannerLandingRoute
  '/meal-planner/': typeof MealPlannerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meal-planner/landing' | '/meal-planner/' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meal-planner/landing' | '/meal-planner' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/meal-planner/landing'
    | '/meal-planner/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealPlannerLandingRoute: typeof MealPlannerLandingRoute
  MealPlannerIndexRoute: typeof MealPlannerIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-planner/': {
      id: '/meal-planner/'
      path: '/meal-planner'
      fullPath: '/meal-planner/'
      preLoaderRoute: typeof MealPlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-planner/landing': {
      id: '/meal-planner/landing'
      path: '/meal-planner/landing'
      fullPath: '/meal-planner/landing'
      preLoaderRoute: typeof MealPlannerLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealPlannerLandingRoute: MealPlannerLandingRoute,
  MealPlannerIndexRoute: MealPlannerIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
